[2023-10-04T12:06:26.793+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_parser.transform scheduled__2023-10-03T04:00:00+00:00 [queued]>
[2023-10-04T12:06:26.798+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_parser.transform scheduled__2023-10-03T04:00:00+00:00 [queued]>
[2023-10-04T12:06:26.799+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2023-10-04T12:06:26.810+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): transform> on 2023-10-03 04:00:00+00:00
[2023-10-04T12:06:26.830+0000] {standard_task_runner.py:57} INFO - Started process 154 to run task
[2023-10-04T12:06:26.836+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_parser', 'transform', 'scheduled__2023-10-03T04:00:00+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/dag_parser.py', '--cfg-path', '/tmp/tmpu6eafu5d']
[2023-10-04T12:06:26.838+0000] {standard_task_runner.py:85} INFO - Job 257: Subtask transform
[2023-10-04T12:06:26.892+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_parser.transform scheduled__2023-10-03T04:00:00+00:00 [running]> on host cdc53d60e2a1
[2023-10-04T12:06:27.458+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='oleg' AIRFLOW_CTX_DAG_ID='dag_parser' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-10-03T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-03T04:00:00+00:00'
[2023-10-04T12:06:27.778+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:27.811+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2023-10-04T12:06:29.162+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:29.290+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:29.394+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:29.485+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:29.594+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:29.676+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:29.744+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:29.819+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:29.897+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:30.019+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:30.121+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:30.192+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:30.256+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:30.340+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:30.424+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:30.496+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:30.578+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:30.693+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:30.789+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:30.852+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:30.910+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:30.967+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.038+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.089+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.139+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.191+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.243+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.294+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.346+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.398+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.449+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.502+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.558+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.639+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.712+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.766+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.820+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.881+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:31.956+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.020+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.103+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.180+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.271+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.353+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.406+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.459+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.511+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.567+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.621+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.677+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.768+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.841+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.912+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:32.964+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.032+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.085+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.138+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.190+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.247+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.312+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.366+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.417+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.470+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.524+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.580+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.656+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.710+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.776+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.854+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.916+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:33.984+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.040+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.097+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.152+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.207+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.264+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.324+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.380+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.437+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.496+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.555+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.614+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.670+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.724+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.791+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.865+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:34.940+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:35.000+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:35.061+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:35.117+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:35.173+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:35.234+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:35.294+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:35.360+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:35.441+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:35.591+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:35.787+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:35.960+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:36.092+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:36.268+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:36.374+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:36.530+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:36.777+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:37.318+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:37.543+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:37.670+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:37.818+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:37.969+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:38.200+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:38.585+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:38.801+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:38.928+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:39.225+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-10-04T12:06:39.756+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2206, in execute
    self.con.rollback()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_parser.py", line 180, in transform
    jobs['drop'] = jobs['id'].apply(test_include)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/series.py", line 4630, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 1025, in apply
    return self.apply_standard()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 1076, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2834, in pandas._libs.lib.map_infer
  File "/opt/airflow/dags/dag_parser.py", line 78, in test_include
    df = hook.get_pandas_df(sql="select distinct id_vac from vacancies;")
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 219, in get_pandas_df
    return psql.read_sql(sql, con=conn, params=parameters, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 635, in read_sql
    return pandas_sql.read_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2211, in execute
    raise ex from inner_exc
pandas.errors.DatabaseError: Execution failed on sql: select distinct id_vac from vacancies;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

unable to rollback
[2023-10-04T12:06:39.944+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_parser, task_id=transform, execution_date=20231003T040000, start_date=20231004T120626, end_date=20231004T120639
[2023-10-04T12:06:40.222+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 257 for task transform (Execution failed on sql: select distinct id_vac from vacancies;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

unable to rollback; 154)
[2023-10-04T12:06:40.539+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-04T12:06:40.869+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
